#!/bin/bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

[[ $DISPLAY ]] && shopt -s checkwinsize

case ${TERM} in
  xterm*|rxvt*|Eterm|aterm|kterm|gnome*)
    PROMPT_COMMAND=${PROMPT_COMMAND:+$PROMPT_COMMAND; }'printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"'

    ;;
  screen*)
    PROMPT_COMMAND=${PROMPT_COMMAND:+$PROMPT_COMMAND; }'printf "\033_%s@%s:%s\033\\" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"'
    ;;
esac

source /usr/share/bash-completion/bash_completion
source /usr/share/git/completion/git-prompt.sh

# Copied from:
#   https://stackoverflow.com/questions/9457233/unlimited-bash-history
#
# Eternal bash history.
# ---------------------
# Undocumented feature which sets the size to "unlimited".
# http://stackoverflow.com/questions/9457233/unlimited-bash-history
export HISTFILESIZE=
export HISTSIZE=
export HISTTIMEFORMAT="[%F %T] "
# Change the file location because certain bash sessions truncate .bash_history file upon close.
# http://superuser.com/questions/575479/bash-history-truncated-to-500-lines-on-each-login
export HISTFILE=~/.bash_eternal_history
# Force prompt to write history after every command.
# http://superuser.com/questions/20900/bash-history-loss
PROMPT_COMMAND="history -a; $PROMPT_COMMAND"
# End copy-paste

export PAGER="/usr/bin/most -s"
export BROWSER="/usr/bin/most -s"
export EDITOR="vim"
export VISUAL="vim"
export GREP_COLOR="1;33"

alias extraer='tar -xvpzf'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias ll='ls -hlp --color=auto --group-directories-first'
alias grep='grep --color=auto'
alias ipython='ipython --no-banner --no-confirm-exit'


export LS_COLORS='*.py=1;38:*.m=1;38:*.awk=1;38:*.tex=1;38:*.sql=1;38:*.csv=1;33:di=1;37;104:*.pyc=1;30'

# regular colors
K="\033[0;30m"    # black
R="\033[0;31m"    # red
G="\033[0;32m"    # green
Y="\033[0;33m"    # yellow
B="\033[0;34m"    # blue
M="\033[0;35m"    # magenta
C="\033[0;36m"    # cyan
W="\033[0;37m"    # white

# emphasized (bolded) colors
EMK="\033[1;30m"
EMR="\033[1;31m"
EMG="\033[1;32m"
EMY="\033[1;33m"
EMB="\033[1;34m"
EMM="\033[1;35m"
EMC="\033[1;36m"
EMW="\033[1;37m"

# background colors
BGK="\[\033[40m\]"
BGR="\[\033[41m\]"
BGG="\[\033[42m\]"
BGY="\[\033[43m\]"
BGB="\[\033[44m\]"
BGM="\[\033[45m\]"
BGC="\[\033[46m\]"
BGW="\[\033[47m\]"

RESET_COLOR="\033[0m"

# user's color
UC=$M

if [[ $(whoami) == "root" ]]
then
        # root's color
        UC=$Y
        echo -e "${C}May the source be with you...${RESET_COLOR}"
fi

PS1="$UC[$W\t$UC][$W\u@\h$UC][$W\w"'$(__git_ps1 " (%s)")'"$UC]$RESET_COLOR\n\$ "

PATH=~/.local/bin:$PATH
